database:
  adapter: postgresql
  encoding: unicode
  database: taller-integracion_development
  pool: 5
  username: taller-integracion
  password: g5tallerintegracion

stocks_management_system:
  public_key: grupo5
  private_key: P9A6XoK8

vtiger:
  username: grupo5
  accessKey: NRh3qzBhggdEoMfz

orders_sftp_system:
  user: grupo5
  password: 823823k
  url: sftp://integra.ing.puc.cl/

mailer:
  domain: "gmail.com"
  user_name: "g5.taller.integracion"
  password: "Nd1T.67hq"

domain:
  host: "integra5.ing.puc.cl"
  port: 8080