database:
  adapter: postgresql
  encoding: unicode
  database: taller-integracion_development
  pool: 5
  username: taller-integracion
  password: g5tallerintegracion

stocks_management_system:
  public_key: grupo5
  private_key: P9A6XoK8

vtiger:
  username: grupo5
  accessKey: NRh3qzBhggdEoMfz

orders_sftp_system:
  user: grupo5
  password: 823823k
  url: integra.ing.puc.cl
  root: "/home/grupo5/Pedidos/"

mailer:
  domain: "gmail.com"
  user_name: "g5.taller.integracion"
  password: "Nd1T.67hq"

domain:
  host: "integra5.ing.puc.cl"
  port: 80

cloudamqp:
  url: "amqp://xaueclvb:SHDpRFouEJqZqImaRvImoel5HJA2VvKh@tiger.cloudamqp.com/xaueclvb"